[+] 更新提示.
unionofblackbean/UBBDispenserShulkerBoxCrashFixer pull request #3
Opened 2021-02-16 12:43 UTC by Micalhl

My English is not good, I'm afraid you can't understand it, so I wrote the commit message in Chinese.

本次 Commit 共包含以下内容:
- 现在, 你可以自定义取消事件后的提示信息了. 在取消事件后,会获取周围 10 格内的所有玩家并分别发送提示. 并向控制台告知有谁可能触发了此Bug.
- 信息现在可以去语言文件中修改, 配置文件也指定了语言, 语言即为文件名, 你可以自己写语言文件, 默认提供了英文和中文.
- 优化了主类代码结构.
- 推进版本号.

2021-03-04 00:24 UTC, leungyauming requested changes
把版本號改一改就行了

2021-03-04 00:24 UTC, leungyauming commented on build.gradle
> +version '0.0.3'
version 應該是 '0.0.3-dev'

2021-03-04 14:46 UTC, Micalhl commented on build.gradle
> +version '0.0.3'
我刚刚又推送了一个 commit, 您看一下.

2021-03-05 04:45 UTC, leungyauming approved these changes

2021-03-05 04:51 UTC, merged